# Site settings
  # Note: after inputting your content into the "" you may need to stop and restart jekyll server for changes to take effect.

title: "TITLE GOES HERE"
subtitle: "SUBTITLE GOES HERE"
description: "DESCRIPTION GOES HERE"
baseurl: ""

# Index settings
greeting: #deletme "GREETING GOES HERE"
subgreetingone: #deletme "SUBGREETING GOES HERE"
subgreetingtwo: #deletme "SUBGREETING GOES HERE"

google_tracking_id: # ENTER GOOGLE ID Here, Starts with "UA"

# Build settings
gems: [jekyll-paginate, jekyll-feed]

theme: simpol-jekyll-theme

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 12
exclude: ["package.json","README.md"]
