# Site settings
title: Simpol Theme
subtitle: #enter tagline in the quotation marks, deleting this note "..."
description: #enter description in the quotation marks, deleting this note "..."
baseurl: ""

# Index settings
greeting: #enter greeting in the quotation marks, deleting this note ""

google_tracking_id: # ENTER GOOGLE ID Here, Starts with "UA"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 12
exclude: ["package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
theme: simpol-jekyll-theme
